server:
  port: 8086
management:
  server:
    port: 9001
    address: 127.0.0.1
spring:
  data:
    mongodb:
       url: mongodb+srv://bootcam:akOU0Wt6DZbORQrD@cluster0.o44govo.mongodb.net/bootcam?retryWrites=true&w=majority
       database: bootcam45
