server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb+srv://bootcam:akOU0Wt6DZbORQrD@cluster0.o44govo.mongodb.net/bootcam?retryWrites=true&w=majority
  kafka:
    consumer:
      group-id: my-group
      bootstrap-servers: localhost:9092
    producer:
      properties:
          spring:
             json:
                trusted:
                    packages=com.nttdata.bootcam.banca.consulta.producto.infrastructure.event

                         
springdoc:
    api-docs:
      groups:
        enabled: true
      path: /swagger-doc/v3/api-docs
    swagger-ui:
      path: /swagger-doc/swagger-ui.html