server:
  port: 8086
management:
  server:
    port: 9001
    address: 127.0.0.1
spring:
  data:
    mongodb:
       url: mongodb+srv://ingwaltereduardo:BTFZ4v2qwbnNWByQ@clustertransaction.bxifyao.mongodb.net/bancatransactiondb?retryWrites=true&w=majority
       database: bancatransactiondb